<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 static/textures/models/office_cubicle/scene.gltf
Author: Sinko Peso (https://sketchfab.com/samonuske)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-cubicle-ecb40d53801447879197c7d6f414fa93
Title: Office Cubicle
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/static\textures\models\office_cubicle\scene.gltf')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, -Math.PI]}>
      <T.Group
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <T.Mesh
          geometry={gltf.nodes.Escritorio_Cerrado_Material_0.geometry}
          material={gltf.materials.Material}
          position={[-500.31, 371.38, 771.48]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <T.Mesh
          geometry={gltf.nodes.Silla_Material006_0.geometry}
          material={gltf.materials['Material.006']}
          position={[-485.07, 352.28, 450.25]}
          rotation={[-3.14, -1.57, -3.14]}
          scale={17.38}
        />
        <T.Mesh
          geometry={gltf.nodes.Archivador_Material_0.geometry}
          material={gltf.materials.Material}
          position={[-1197.99, 421.99, 1216.85]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        />
        <T.Mesh
          geometry={gltf.nodes.Hoja_Material004_0.geometry}
          material={gltf.materials['Material.004']}
          position={[-213.38, 375.38, 720.29]}
          rotation={[-Math.PI / 2, 0, 2.89]}
          scale={[52.82, 76.27, 52.82]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cubiculo_Material_0.geometry}
          material={gltf.materials.Material}
          position={[-500, 400, 1078.42]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[10, 516, 100]}
        />
        <T.Mesh
          geometry={gltf.nodes.Taza_Material005_0.geometry}
          material={gltf.materials['Material.005']}
          position={[-785.72, 365.94, 760.88]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={29.75}
        />
        <T.Mesh
          geometry={gltf.nodes.Horario_Material002_0.geometry}
          material={gltf.materials['Material.002']}
          position={[-18.1, 639.43, 441.31]}
          rotation={[-1.57, -0.02, -Math.PI / 2]}
          scale={[8.45, 8.45, 17.62]}
        />
        <T.Mesh
          geometry={gltf.nodes.Segundero_Material002_0.geometry}
          material={gltf.materials['Material.002']}
          position={[-19.23, 639.43, 441.31]}
          rotation={[-1.13, -0.02, -Math.PI / 2]}
          scale={[12.6, 12.6, 26.28]}
        />
        <T.Mesh
          geometry={gltf.nodes.Reloj_Material003_0.geometry}
          material={gltf.materials['Material.003']}
          position={[-14.87, 639.43, 441.31]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[71.94, 71.94, 5.89]}
        />
        <T.Mesh
          geometry={gltf.nodes.Minutero_Material002_0.geometry}
          material={gltf.materials['Material.002']}
          position={[-18.1, 639.43, 441.31]}
          rotation={[-Math.PI / 4, -0.02, -Math.PI / 2]}
          scale={[12.6, 12.6, 26.28]}
        />
        <T.Mesh
          geometry={gltf.nodes.Computador_Material006_0.geometry}
          material={gltf.materials['Material.006']}
          position={[-487.56, 551.37, 755.32]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[136.9, 8.38, 100]}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
